server:
  port: 14159

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
logging:
  level:
    org.springframework.security: DEBUG

app:
  openapi:
    server:
      url: http://localhost:14159
      description: LocalDev