server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharp
    username: scott
    password: tiger
  jpa:
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    hs512Key: "0nQEx2CO15Sv4+AfdkqH5nadsvty3PAil+IJ7p08h/2HXYj2pnW5j18DPSTjJqEit0zumIkF0Ll7xtVvWAweyQ=="